### ISSUE TITLE
verberg niet-gepubliceerde zalen

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#10]
Het zou mooi zijn als de niet-gepubliceerde zalen niet zichtbaar zijn in de dropdown lijst bij het aanmaken van een session. 

![schermafdruk 2018-02-21 08 43 40](https://user-images.githubusercontent.com/639822/36468337-5c689594-16e3-11e8-86f9-8a4eb74cb72c.png)

**Comment by roland-d** [comment]
@hans2103 Nu worden alleen de gepubliceerde zalen getoond.

**Comment by hans2103** [comment]
Ik zie het. Top
<img width="475" alt="schermafdruk 2018-02-24 10 02 19" src="https://user-images.githubusercontent.com/639822/36627882-d10cf8dc-1949-11e8-80c3-bcdc36050ebf.png">
