### ISSUE TITLE
[session] PHP Notice undefined variable room

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#12]
Het zou mooi zijn dat ik op frontend de naam van een room in beeld krijg in plaats van een PHP Notice. 

> Notice: Undefined property: stdClass::$room in /Users/hans2103/Sites/joomladagen/public_html/templates/jd18nl/html/com_conference/days/default.phpon line 78

https://github.com/stichtingsympathy/conference/blob/78adcf79c36552c876b08f97a1e5ad7bc6a8f90c/code/components/com_conference/views/days/tmpl/default.php#L74

**Comment by hans2103** [comment]
Ik heb in de template override een wijziging aangebracht om de room name zichtbaar te krijgen. In de extensie is het nog niet correct en ik weet niet of ik de wijziging juist gedaan heb. 

#origineel
https://github.com/stichtingsympathy/conference/blob/f2d52bf025b1a796b4fa30c86b3c6a213e2bd7ad/code/components/com_conference/views/days/tmpl/default.php#L73-L75

# template override
https://github.com/hans2103/joomladagen.nl/blob/71a62698a25e577d37984677400daa0cfc929b9f/public_html/templates/jd18nl/html/com_conference/days/default.php#L80-L82

**Comment by sanderpotjer** [comment]
@hans2103 heb je helemaal goed gedaan :)

Dus ook in basis aangepast nu.
