### ISSUE TITLE
[session] doorklikken naar niveau

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#13]
Het zou mooi zijn als je op het programmaovezicht bent je kunt doorklikken naar de uitleg over een bepaald niveau. De link gaat nu naar /programma.

**Comment by sanderpotjer** [comment]
@hans2103 wat is "de uitleg"? Deze pagina? https://www.joomladagen.nl/niveaus

**Comment by hans2103** [comment]
Correct

**Comment by sanderpotjer** [comment]
Fixed
