### ISSUE TITLE
[session] titel van algemene sessie verschijnt niet

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#14]
Het zou mooi zijn dat sessies die gepland zijn in de algemene ruimte ook op het scherm komen. 
![schermafdruk 2018-02-21 11 10 13](https://user-images.githubusercontent.com/639822/36474452-cf4fed8c-16f7-11e8-81e8-4dd3001cfd6f.png)

**Comment by roland-d** [comment]
@hans2103 Ik zie niet wat er hier mist. Kan je aangeven welke sessie je mist?

**Comment by hans2103** [comment]
overleg gehad via Glip. Issue is duidelijk.
De titel van een sessie in de algemene ruimte is niet zichtbaar.

**Comment by roland-d** [comment]
Dit is nu opgelost met commit e6e2c28
