### ISSUE TITLE
[session] meerdere sprekers

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#15]
Het zou mooi zijn als het overzicht aan de voorzijde van de website meerdere sprekers komen te staan, als er ook meerdere sprekers aan een sessie toegewezen zijn.
_Workshop RSForm!Pro_ staat nu slechts één van de twee toegewezen sprekers

**Comment by hans2103** [comment]
@sanderpotjer Met de doorgevoerde wijziging worden sessies zonder sprekers niet meer getoond.

**Comment by sanderpotjer** [comment]
Fixed na pull
