### ISSUE TITLE
[room] subtitle bij invoer

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#16]
Het zou mooi zijn als je bij de invoer van een zaal ook een subtitel kunt opgeven, waarin je de eigenlijke naam van de zaal in plaatst. 
Het huidige sponsorpakket van JoomlaDagen 2018 geeft aan dat zalen vernoemd worden naar een sponsor. 
Voor de vindbaarheid is het handig als je ook de eigenlijke naam plaatst.

**Comment by roland-d** [comment]
@hans2103 Dit kan getest worden

**Comment by hans2103** [comment]
ziet er goed uit
