### ISSUE TITLE
[spreker] weergave van gegeven presentaties

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/conference#17]
Het zou mooi zijn als de lijst van presentaties voorzien kan worden met het jaartal / editie van JoomlaDagen in omgekeerde volgorde. Nu staat de oudste bovenaan.

![schermafdruk 2018-02-23 11 06 12](https://user-images.githubusercontent.com/639822/36588815-9d0caed0-1889-11e8-8cdf-4c25d07cdf1f.png)

**Comment by sanderpotjer** [comment]
@hans2103 want het is wel wenselijk dat oudere presentaties ook getoond worden? Normaal deden we alleen van deze editie

**Comment by hans2103** [comment]
Goed plan... 'oude' presentaties heb ik gedepubliceerd. Ze blijven alsnog verschijnen in de lijst
@roland-d pak jij het verder op?

**Comment by roland-d** [comment]
@hans2103 Ik heb de query aangepast, gedepubliceerde presentaties worden niet meer getoond. Tevens heb ik de order by de ordering kolom toegepast.

**Comment by hans2103** [comment]
Ik heb het gezien. Top!
