### ISSUE TITLE
[sprekerspagina] Layout behoeft styling

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/conference#20]
@hans2103 Ik heb eindelijk de URLs werkend onder SEF voor de "Mijn Sprekerspagina". Deze pagina's moeten nu nog wel gestyled worden.

Blijkbaar moet er ook nog wat JavaScript geladen worden:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/359377/36644264-26cf1c78-1a8a-11e8-80cb-45ed1c53f4b3.png">

Dit betreft denk ik dan de core.js.

**Comment by hans2103** [comment]
js issue opgelost door in templateHelper core.js en validation.js niet te verwijderen zodra je in layout edit bent van com_conference

**Comment by roland-d** [comment]
@hans2103 De styling van de pagina moet nog wel gebeuren.

**Comment by hans2103** [comment]
styling toegepast
